ALTER TABLE "Evaluation"
ALTER COLUMN "score" TYPE DOUBLE PRECISION USING "score"::DOUBLE PRECISION,
ALTER COLUMN "communication" TYPE DOUBLE PRECISION USING "communication"::DOUBLE PRECISION,
ALTER COLUMN "anamnesis" TYPE DOUBLE PRECISION USING "anamnesis"::DOUBLE PRECISION,
ALTER COLUMN "reasoning" TYPE DOUBLE PRECISION USING "reasoning"::DOUBLE PRECISION,
ALTER COLUMN "safety" TYPE DOUBLE PRECISION USING "safety"::DOUBLE PRECISION,
ALTER COLUMN "exams" TYPE DOUBLE PRECISION USING "exams"::DOUBLE PRECISION,
ALTER COLUMN "closing" TYPE DOUBLE PRECISION USING "closing"::DOUBLE PRECISION,
ALTER COLUMN "organization" TYPE DOUBLE PRECISION USING "organization"::DOUBLE PRECISION,
ALTER COLUMN "treatmentScore" TYPE DOUBLE PRECISION USING "treatmentScore"::DOUBLE PRECISION,
ALTER COLUMN "diagnosisScore" TYPE DOUBLE PRECISION USING "diagnosisScore"::DOUBLE PRECISION;
